#!/usr/bin/env python3
"""Extract MHR joint names from the JIT body model and emit a C++ header.

Output: src/mhr_joint_table.h  (compiled in via bvh_writer.cpp).

The names come from `character_torch.skeleton.joint_names` inside mhr_model.pt.
They never change between checkpoints (the body skeleton is fixed), so we bake
them in at build time rather than reading them from body_model.lbs (which does
not store names today).

Override the model path with $MHR_MODEL_PT.
"""
from __future__ import annotations
import os
import sys
import textwrap
from pathlib import Path

DEFAULT_PT = "/home/ammar/Documents/3dParty/sam-3d-body/checkpoints/sam-3d-body-dinov3/assets/mhr_model.pt"
OUT_HEADER = Path(__file__).resolve().parents[1] / "src" / "mhr_joint_table.h"


def main() -> int:
    pt = os.environ.get("MHR_MODEL_PT", DEFAULT_PT)
    if not Path(pt).exists():
        print(f"missing {pt}; set MHR_MODEL_PT or place mhr_model.pt there",
              file=sys.stderr)
        return 1

    import torch
    model = torch.jit.load(pt, map_location="cpu")
    skel = None
    for n, m in model.named_modules():
        if n == "character_torch.skeleton":
            skel = m
            break
    if skel is None:
        print("could not find character_torch.skeleton in model", file=sys.stderr)
        return 1
    names = list(skel.joint_names)
    parents = skel.joint_parents.tolist()

    lines = []
    lines.append("// AUTO-GENERATED by scripts/build_joint_table.py — DO NOT EDIT BY HAND.")
    lines.append("//")
    lines.append(f"// Source: {pt}")
    lines.append(f"// Joints: {len(names)}")
    lines.append("#pragma once")
    lines.append("namespace mhr_joint_table {")
    lines.append(f"constexpr int N_JOINTS = {len(names)};")
    lines.append("constexpr const char* NAMES[N_JOINTS] = {")
    for i, n in enumerate(names):
        lines.append(f'    "{n}",')
    lines.append("};")
    lines.append("constexpr int PARENTS[N_JOINTS] = {")
    for i, p in enumerate(parents):
        lines.append(f"    {p},")
    lines.append("};")
    lines.append("}  // namespace mhr_joint_table")

    OUT_HEADER.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_HEADER}  ({len(names)} joints)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
